substitutions:
  name: "furnace"
  friendly_name: Furnace Room
  frame_type: esp-idf
  board: esp32-c3-devkitm-1

packages:
  device_base: !include /config/esphome/packages/sg_base.yaml

esp32:
  variant: ESP32C3

wifi:
  manual_ip:
    gateway: !secret chaloupkaabode_gateway
    subnet: !secret chaloupkaabode_subnet
    static_ip: !secret firebox

esphome:
  name_add_mac_suffix: false

bluetooth_proxy:
  active: true

spi:
  miso_pin: GPIO5
  clk_pin: GPIO4

sensor:
  - platform: max6675
    name: "Cottage Gas Furnace"
    cs_pin: GPIO7
    update_interval: 64s

  - platform: dht
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
    # model: AM2302
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    update_interval: 75s
